# Book settings
title                       : CIS 105 Book
author                      : Kai Lu
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : ""  # A path to the book logo
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")


# Information about where the book exists on the web
repository:
  url                       : https://github.com/kailu3/105-book

execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex
